### PR TITLE
chore: update golang dependencies 

### PR DESCRIPTION
**Pull request by ngocpea**
## Context

PR updates golang dependencies for SOC2 compliance 

JIRA ticket: https://cultureamp.atlassian.net/browse/CSRE-2241

`go get -u ./...`
`go get -t -u` to test
`go mod tidy` to get rid of unused dependencies
`go build` to make sure it works

### CODE REVIEW

**Review by ctgardner — APPROVED** [review]
I trust this has been tested

**Comment by ngocpea** [comment]
> I trust this has been tested



> I trust this has been tested

Hey @ctgardner Thanks for the review! I tested that it builds but deploying cfparams itself, I haven't done that - not sure exactly how to 😅

**Comment by jamestelfer** [comment]
`go test ./...` will run tests, `go get -t -u` only updates test dependencies. Were the tests run?

**Comment by ngocpea** [comment]
> 

Thanks @jamestelfer ah yes, thanks very much for that

```
go test ./...                        
?       github.com/cultureamp/cfparams/parameterstore   [no test files]
ok      github.com/cultureamp/cfparams  4.349s
```

**Pull request merged**
